# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute Euclidean distance matrix by rows
#' 
#' Used in consmx function
#' 
#' @param x A numeric matrix.
ED1 <- function(x) {
    .Call('_sc3min_ED1', PACKAGE = 'sc3min', x)
}

#' Compute Euclidean distance matrix by columns
#' 
#' Used in sc3-funcs.R distance matrix calculation
#' and within the consensus clustering.
#' 
#' @param x A numeric matrix.
ED2 <- function(x) {
    .Call('_sc3min_ED2', PACKAGE = 'sc3min', x)
}

#' Co-association matrix computation
#' 
#' Computes co-association matrix given cluster labels
#'res /= dat.n_cols;
#' 
#' @param dat a matrix containing clustering solutions in columns
consmx <- function(dat) {
    .Call('_sc3min_consmx', PACKAGE = 'sc3min', dat)
}

#' Consensus matrix computation
#' 
#' Computes consensus matrix given a co-association matrix
#' 
#' @param matrix a matrix containing co-association matrix
#' @param k number of clusters
consensus <- function(matrix, k) {
    .Call('_sc3min_consensus', PACKAGE = 'sc3min', matrix, k)
}

#' Graph Laplacian calculation
#' 
#' Calculate graph Laplacian of a symmetrix matrix
#' 
#' @param A symmetric matrix
#' @export
norm_laplacian <- function(A) {
    .Call('_sc3min_norm_laplacian', PACKAGE = 'sc3min', A)
}

#' Matrix left-multiplied by its transpose
#' 
#' Given matrix A, the procedure returns A'A.
#' 
#' @param x Numeric matrix.
tmult <- function(x) {
    .Call('_sc3min_tmult', PACKAGE = 'sc3min', x)
}

